### PR TITLE
Finalise UI for 1.3

### LINKED ISSUE #130: Update UI (scrollbar and background)

### LINKED ISSUE #131: Select Command
To open individual recipe

### LINKED ISSUE #132: Close Command
To close individual recipe

### PR DESCRIPTION
**Pull request by daongochieu2810**

### CODE REVIEW

**Review by TianYong-Goh — APPROVED** [review]
lgtm

**Review by oliviajohansen — APPROVED** [review]
lgtm

**Review by caitlinjee — APPROVED** [review]
lgtm

**Review by caitlinjee — COMMENTED** [review]
don't forget to update ug and dg!

**Review by jiaqi20 — APPROVED** [review]
lgtm

**Pull request merged**
