### PR TITLE
Search Recipe

### LINKED ISSUE #8: As a new user, I can search my recipes on the computer
so that I can search my recipes on the computer

### PR DESCRIPTION
**Pull request by TianYong-Goh**

### CODE REVIEW

**Review by daongochieu2810 — CHANGES_REQUESTED** [review]
Can you change the search to show all items that contain the keyword ? Right now if I search for ```lex``` , ```Alex``` will not appear

**Review by daongochieu2810 — APPROVED** [review]
lgtm

**Review by jiaqi20 — APPROVED** [review]
lgtm

**Review by caitlinjee — APPROVED** [review]
lgtm

**Review by oliviajohansen — APPROVED** [review]
lgtm

**Pull request merged**
