### PR TITLE
Update SearchRecipeCommand and add RecommendCommand

### LINKED ISSUE #96: Search recipe with tag filter

### LINKED ISSUE #98: Search recipe with ingredient(s) filter

### LINKED ISSUE #101: Recommend recipes based on user's fridge

### LINKED ISSUE #105: Add recommend command

### PR DESCRIPTION
**Pull request by caitlinjee**

### CODE REVIEW

**Review by oliviajohansen — COMMENTED** [review]
looks ok, are you planning to add tests?

**Review by oliviajohansen — APPROVED** [review]
lgtm

**Review by daongochieu2810 — APPROVED** [review]

**Review by TianYong-Goh — APPROVED** [review]
lgtm

**Review by jiaqi20 — APPROVED** [review]
lgtm

**Pull request merged**
