### PR TITLE
Show calories and Remove Email and Address Class

### LINKED ISSUE #70: Calculate and Show the Total Calorie

### LINKED ISSUE #81: Remove the unrelated Field from Ab3

### PR DESCRIPTION
**Pull request by TianYong-Goh**

### CODE REVIEW

**Review by daongochieu2810 — APPROVED** [review]
Rmb to level the branch with master 1st

**Review by jiaqi20 — APPROVED** [review]
lgtm

**Review by caitlinjee — APPROVED** [review]
lgtm

**Review by oliviajohansen — APPROVED** [review]
lgtm

**Pull request merged**
